Repository LuizCarlosdeSouzaAlmeida/inlumem, pull requests merged in 2023-08, with the labels that each got.

#17 Melhorias main menu & loading
  Assets/Scenes/LoadingScene.unity
  Assets/Scenes/MainMenuScene.unity
  Assets/UI/Loader.cs
  Assets/UI/LoaderCallback.cs
Labels: melhoria

#22 Correções diversas
  Assets/Scenes/InitialCutscene.unity
  Assets/Scenes/SampleScene.unity
  Assets/Scenes/SampleScene.unity.orig.meta
  Assets/Script/UIMessages.meta
  Assets/TimeManager.cs
Labels: bug

#23 Implementação do parallax
  Assets/Prefabs/Scenario/Detalhes/poste1.prefab
  Assets/Scenario/Coisas que soltam luz/Tocha/Tocha.prefab
  Assets/Scenario/Sprites Scenario/Parallax0.png
  Assets/Scenario/Sprites Scenario/Parallax0.png.meta
  Assets/Scenario/Sprites Scenario/Parallax1.png
  Assets/Scenario/Sprites Scenario/Parallax1.png.meta
  Assets/Scenario/Sprites Scenario/Parallax2.png
  Assets/Scenario/Sprites Scenario/Parallax2.png.meta
  Assets/Scenario/Sprites Scenario/Parallax3.png
  Assets/Scenario/Sprites Scenario/Parallax3.png.meta
  Assets/Scenes/InitialCutscene.unity
  Assets/Scenes/LoadingScene.unity
  Assets/Scenes/MainMenuScene.meta
  Assets/Scenes/MainMenuScene.unity
  Assets/Scenes/Parallax.cs
  Assets/Scenes/Parallax.cs.meta
  Assets/Scenes/SampleScene.unity
Labels: feature, melhoria, assets

#24 Melhorias textuais
  Assets/Prefabs/Scenario/Detalhes/poste1.prefab
  Assets/Scenes/InitialCutscene.unity
  Assets/Scenes/LoadingScene.unity
  Assets/Scenes/MainMenuScene.unity
  Assets/Scenes/SampleScene.unity
  Assets/Script/UIMessages/TimedMessageTrigger.cs
  Assets/Script/UIMessages/TimedMessageTrigger.cs.meta
  Assets/TextMesh Pro/Fonts/Ancient Modern Tales.otf
  Assets/TextMesh Pro/Fonts/Ancient Modern Tales.otf.meta
  Assets/TextMesh Pro/Resources/Fonts & Materials/Ancient Modern Tales SDF.asset
  Assets/TextMesh Pro/Resources/Fonts & Materials/Ancient Modern Tales SDF.asset.meta
Labels: melhoria, assets

#26 Fix bug pós morte
  Assets/Character/Cain/Animations/CainTeste.controller
  Assets/Character/Cain/Flecha/Projectile.cs
  Assets/Character/Cain/Script/PlayerMeleeAttack.cs
  Assets/Character/Cain/Script/PlayerMovement.cs
  Assets/Character/Cain/Script/PlayerShield.cs
  Assets/Character/Inimigos/Boss Summoner/Spitter/Projectile/SpitterProjectileScript.cs
  Assets/PlayerDeathCheckPoint.cs
  Assets/Scenes/SampleScene.unity
  Assets/Script/Health/Health.cs
Labels: bug, melhoria

#29 Mais correções
  Assets/Audio/MenuSoundScript.cs
  Assets/Audio/OverworldSoundScript.cs
  Assets/Scenes/InitialCutscene.unity
  Assets/Scenes/SampleScene.unity
  Assets/Scenes/Timeline.playable
  Assets/Script/UIMessages/MessageTrigger.cs
Labels: bug, melhoria

#31 Ajustes
  Assets/DeathMenu.cs
  Assets/Prefabs/PauseMenuCanvas.prefab
  Assets/Prefabs/PauseMenuCanvas.prefab.meta
  Assets/Scenes/BossCutscene.unity
  Assets/Scenes/MainMenuScene.unity
  Assets/Scenes/SampleScene.unity
  Assets/Scenes/SceneBoss.unity
  Assets/Script/Health/BossHealthbar.cs
  Assets/UI/Loader.cs
  Assets/UI/PauseMenu.cs
  ProjectSettings/TagManager.asset
Labels: melhoria

#32 Creditos
  Assets/BossScript.cs
  Assets/Scenes/SceneBoss.unity
  Assets/Scenes/SceneBoss.unity.orig
  Assets/Script/Health/Health.cs
  Assets/UI/CreditsUI.cs
  Assets/UI/CreditsUI.cs.meta
Labels: feature
